---
title: "analysis"
output: html_document
date: "2026-02-16"
---

```{r}
WKDir ="/Users/z5161362/OneDrive - DPIE/Documents/PhD/spatRast/"
source(paste0(WKDir,"R/cost_distance.r"))

library(APCalign)

library(ggplot2)
library(tidyterra)
library(ggnewscale)
library(ggrepel)
library(patchwork)
```

```{r}
#“Distances are multiplied with the friction, thus to get the cost-distance, the friction surface must express the cost per unit distance (speed) of travel”

# Workflow

setup_terra_for_large_rasters(
  tempdir = paste0(WKDir, "output_wol/temp/"),
  memfrac = 0.6,
  verbose = TRUE
)

 cost <- load_cost_raster(paste0(WKDir,"data_wol/processing/wol/cost.tif"))
 track <- load_tracks(paste0(WKDir,"data_wol/tracks/tracks_clean.rds"))
 burn_tracks(cost, track, filename=paste0(WKDir,"output_wol/burn.tif"))
 burn <- terra::rast(paste0(WKDir,"output_wol/burn.tif"))

run_cost_dist(burn, filename= (paste0(WKDir,"output_wol/cost_surface.tif")), tmp_fn= (paste0(WKDir,"output/temp/")), overwrite = TRUE, maxiter = 25)

cost_surface <- terra::rast(paste0(WKDir,"output_wol/cost_surface.tif"))

cost_surface_wol <-  terra::crop(cost_surface, vect(np_wol_gda94), mask=TRUE) # run and check
terra::writeRaster(cost_surface_wol, paste0(WKDir, "output_wol/cost_surface_wol.tif"), overwrite = TRUE) ## Commented out to prevent re-writing
cost_surface_wol <- terra::rast(paste0(WKDir, "output_wol/cost_surface_wol.tif"))

plot(cost_surface_wol)

```

```{r}
# combining herb and iNat
occ_wol_comb <- rbind(occ_wol_gda94, occ_wol_herb_gda94)
occ_wol_comb <- dplyr::bind_rows(list(occ_wol_gda94, occ_wol_herb_gda94), .id = 'source') 
occ_wol_comb <- occ_wol_comb %>%
    mutate(source = recode(source, "1" = "iNaturalist", "2" = "Herbarium"))

occ_wol_cost <- pts_cost(occ_wol_comb, cost_surface_wol) # point cost
```


```{r}
occ_wol_cost <- occ_wol_cost %>% filter(uncertainty < 300) # filtering out points with more than 300m of uncertainty in location
tax_resources <- load_taxonomic_resources() # load this first run of session
status <- native_anywhere_in_australia(as.list(occ_wol_cost$species), resources = tax_resources) # using APCalign to extract native/introduced status
occ_wol_cost <- cbind(occ_wol_cost, status$native_anywhere_in_aus)
```


```{r}
occ_wol_text <- occ_wol_cost %>% filter(pts_cost > 300) # creating a subset of labels for plotting

buff <- st_buffer(np_wol_gda94, dist = 500, nQuadSegs = 30) # 500m buffer for plotting
tr_wol <- st_intersection(wol_tr_gda94, buff) 

occ_wol_cost <- dist_points_to_path(occ_wol_cost, tr_wol) # Calculates crow distance from point to the path.
```

```{r}
bb <- st_bbox(np_wol)
qu_wol <- bb %>% 
  opq() %>%
  add_osm_feature(
    key= "highway",
    value = c("primary", "secondary", "tertiary","residential", "unclassified", "service", "escape", "access track", "track", "track", "footway", "steps", "path", "path")
    )

osm_data_wol <- osmdata_sf(qu_wol)

osm_lines_wol <-osm_data_wol$osm_lines
osm_gda94_wol <- st_transform(osm_lines_wol, crs = crs(cost_surface_wol))
bb_wol <- st_bbox(np_wol_gda94)
osm_background_wol <- st_crop(osm_gda94_wol, bb_wol)

osm_road_wol <-osm_background_wol[osm_background_wol$highway %in% c("trunk", "primary", "primary_link", "secondary", "secondary_link", "tertiary", "tertiary_link", "motorway", "motorway_link"),]

tr_wol_croped <- st_intersection(tr_wol, np_wol_gda94)

occ_wol_cost_inat$status.native_anywhere_in_aus <- factor(
  occ_wol_cost_inat$status.native_anywhere_in_aus,
  levels = c("unknown", "native", "introduced")
)
occ_wol_cost_inat <- occ_wol_cost_inat[order(occ_wol_cost_inat$status.native_anywhere_in_aus == "introduced"), ]
plot(osm_data_wol$osm_lines$geometry)
```

```{r}
ml <- read.csv(paste0(WKDir,"Map locations.csv"), header = TRUE)
ml_sf <- st_as_sf(ml, coords = c("long", "lat"), crs = 4326)
ml_sf <- st_transform(ml_sf, crs = crs(cost_surface_wol))

bb_wol <- st_bbox(np_wol_gda94)
ml_wol <- st_crop(ml_sf, bb_wol)
ml_wol <- ml_wol[ml_wol$location != "Wollemi National Park",]
```

```{r}
plot_cost(cost_surface=cost_surface_wol, osm_background=osm_background_wol, osm_road=osm_road_wol, tr=tr_wol_croped, occ_cost=occ_wol_cost_inat, ml_pk=ml_wol, cell=100000000, fn=paste0(WKDir,"output_wol/plots/cost_rast_wol_inat.png"))

plot_cost(cost_surface=cost_surface_wol, osm_background=osm_background_wol, osm_road=osm_road_wol, tr=tr_wol_croped, occ_cost=occ_wol_cost_herb, ml_pk=ml_wol, cell=100000000, fn=paste0(WKDir,"output_wol/plots/cost_rast_wol_herb.png"))
```


```{r}
grid_sf <- grid_points_cost(n=10000, np_outline=np_wol_gda94, tr=tr_wol, cost_surface=cost_surface_wol)
```


```{r}
#cost vers dist plots
# iNaturalist
introduced <- occ_wol_cost %>% filter(status.native_anywhere_in_aus == "introduced")
occ_wol_cost_inat <- occ_wol_cost %>% filter(source == "iNaturalist")
cost_v_dist_plot(grid_sf, occ_wol_cost_inat, extra=TRUE, top_layer_points = introduced, cols=c("#ABC7C9", "#666633", "#669900") , fn = paste0(WKDir,"output_wol/plots/cost_v_dist_inat.png"))

# Herbarium
occ_wol_cost_herb <- occ_wol_cost %>% filter(source == "Herbarium")
cost_v_dist_plot(grid_sf, occ_wol_cost_herb, extra=FALSE, cols= c("#666633","#669900"), fn=paste0(WKDir,"output_wol/plots/cost_v_dist_herb.png"))
```



```{r}
cost <- terra::rast(paste0(WKDir,"data_wol/processing/wol/cost.tif"))
tr_buff <- st_buffer(wol_tr_gda94, dist=30, nQuadSegs = 30)
crop_to_track <-terra::crop(cost, tr_buff, mask=TRUE, touches=TRUE)

tr_road <- tr_buff %>% filter(highway_com=="road")

setup_terra_for_large_rasters(
  tempdir = paste0("/Users/z5161362/Downloads/temp/"),
  memfrac = 0.6,
  verbose = TRUE
)

burn_tracks(crop_to_track, tr_road, filename=paste0(WKDir,"output_wol/burn_tracks.tif"))
burn_tr <- terra::rast(paste0(WKDir,"output_wol/burn_tracks.tif"))

run_cost_dist(burn_tr, filename= (paste0(WKDir,"output_wol/cost_track.tif")), tmp_fn= ("/Users/z5161362/Downloads/temp/"), overwrite = TRUE, maxiter = 25)
cost_tr <- terra::rast(paste0(WKDir,"output_wol/cost_track.tif"))
plot(cost_tr)
```

# Tracks plot here





```{r}
# SMALL test 

# Creating small box
bbox <- ext(150.230, 150.280, -33.190, -33.140)
bbox_vect <- as.polygons(bbox)
crs(bbox_vect) <- "EPSG:4283"  
bbox_proj <- project(bbox_vect, crs(cost))
cost_crop_sm <- crop(cost, bbox_proj, mask = TRUE) # Cost
wol_tr_crop_sm <- st_crop(wol_tr_gda94, bbox_proj, mask = TRUE) # Tracks
plot(cost_crop_sm)

cost_sm <- load_cost_raster(cost_crop_sm)
track_sm <- load_tracks(wol_tr_crop_sm)
burn_sm <- burn_tracks(cost_sm, track_sm, tmp_fn= (paste0(WKDir,"output_wol/temp/")))
cost_surface_sm<- run_cost_dist(burn_sm, filename= (paste0(WKDir,"output_wol/cost_surface_sm.tif")), overwrite=TRUE)
cost_surface_sm <- terra::rast(paste0(WKDir,"output_wol/cost_surface_sm.tif"))
plot_cost_with_tracks(cost_surface_sm, tracks = track_sm, filename = "output_wol/plots/cost_rast_sm.png")

# Raster CRS: GDA94 / MGA zone 56 (EPSG:28356)
# Tracks CRS: GDA94 / MGA zone 56 (EPSG:28356)
# Raster dimensions: 2834 rows x 2405 cols (6,815,770 cells)
# Resolution: 2 x 2 m
# Rasterizing tracks onto cost surface...
# Track cells rasterized: 14,905 (0.22% of raster)
# Running costDist (maxiter=50)...
# costDist completed in 11.26 seconds
# Estimated peak memory: 143.9 MB
ext(cost_crop_sm)
```

