---
title: "analysis"
output: html_document
date: "2026-02-16"
---

```{r}
WKDir ="/Users/z5161362/OneDrive - DPIE/Documents/PhD/spatRast/"

source(paste0(WKDir,"R/cost_distance.r"))

library(APCalign)

library(ggplot2)
library(tidyterra)
library(ggnewscale)
library(ggrepel)
library(patchwork)
```

```{r}
#“Distances are multiplied with the friction, thus to get the cost-distance, the friction surface must express the cost per unit distance (speed) of travel”

# Workflow
# calc_cost_to_tracks this one does eveything?

setup_terra_for_large_rasters(
  tempdir = paste0(WKDir, "output/temp/"),
  memfrac = 0.6,
  verbose = TRUE
)

 cost <- load_cost_raster(paste0(WKDir,"data/processing/wol/cost.tif"))
 track <- load_tracks(paste0(WKDir,"data/tracks/tracks_clean.rds"))
 burn_tracks(cost, track, filename=paste0(WKDir,"output/burn.tif"))
 burn <- terra::rast(paste0(WKDir,"output/burn.tif"))

run_cost_dist(burn, filename= (paste0(WKDir,"output/cost_surface.tif")), tmp_fn= (paste0(WKDir,"output/temp/")), overwrite = TRUE, maxiter = 25)

cost_surface <- terra::rast(paste0(WKDir,"output/cost_surface.tif"))

# 142
#75 files


cost_surface_wol <-  terra::crop(cost_surface, vect(np_wol_gda94), mask=TRUE) # run and check
```

```{r}
pts <- do.call(rbind, st_geometry(occ_wol_gda94$geometry)) %>% 
    as_tibble() %>% setNames(c("x","y"))
pts_cost <- extract_point_costs(cost_surface, pts)
occ_wol_gda94 <- cbind(occ_wol_gda94, pts_cost)
occ_wol_gda94$pts_cost<-round(occ_wol_gda94$pts_cost,1)
```



```{r}
occ_wol_gda94 <- occ_wol_gda94 %>% filter(uncertainty < 300) # filtering out points with more than 300m of uncertainty in location

#tax_resources <- load_taxonomic_resources() # load this first run of session
status <- native_anywhere_in_australia(as.list(occ_wol_gda94$species), resources = tax_resources) # using APCalign to extract native/introduced status
occ_wol_gda94 <- cbind(occ_wol_gda94, status$native_anywhere_in_aus)


introduced <- occ_wol_gda94 %>% filter(status.native_anywhere_in_aus == "introduced")
```






```{r}
occ_wol_gda94 <- occ_wol_gda94 %>% filter(uncertainty < 300) # filtering out points with more than 300m of uncertainty in location
occ_wol_gda94_text <- occ_wol_gda94 %>% filter(pts_cost > 300) # creating a subset of lables for plotting

buff <- st_buffer(np_wol_gda94, dist = 500, nQuadSegs = 30) # 500m buffer for plotting
tr <- st_intersection(wol_tr_gda94, buff) 

occ_wol_gda94 <- dist_points_to_path(occ_wol_gda94, tr) # Calculates crow distance from point to the path.
```


```{r}
cost_plot <- ggplot() +
  # cost surface 
      geom_spatraster(data = cost_surface_wol, maxcell=100000000) +
        scale_fill_gradientn(colours=grDevices::hcl.colors(50, "YlOrRd", rev = TRUE), na.value = "grey90") +
          new_scale_colour() +
  # Tracks
      geom_sf(data = tr, aes(geometry=geometry, color = highway_com), key_glyph = draw_key_path, lwd=0.6) +
          scale_color_manual(values=c("#7a7a7a","#4E4E4E","#E69F00","black")) +
              new_scale_fill() +
  # iNat points
      geom_sf(data = occ_wol_gda94, aes(fill = as.factor(status.native_anywhere_in_aus)), shape = 21, colour = "black", size = 3, stroke = 1, inherit.aes = FALSE) +
          scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"), name = "Native Status") +
   # labels
      geom_text_repel(data = occ_wol_gda94_text, aes(label = pts_cost, geometry = geometry), stat = "sf_coordinates", size = 3, fontface = "bold",max.overlaps = Inf) +
  # plot design
      coord_sf() +
      theme_bw() + theme(legend.key = element_rect(fill="grey90")) +
  scale_x_continuous( expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
         labs(title = "Cost Surface with Tracks")
  
ggsave(
  filename = paste0(WKDir,"output/plots/cost_rast_wol.png"),
  width = 40,
  height = 30,
  dpi = 300
)

#geom_sf(data = mask, fill = "white", colour = NA, inherit.aes = FALSE) +
```


```{r}
# Grid points of n
n <- 2000 
grid <- st_sample(st_as_sf(np_wol_gda94), size = n, type = "regular")
grid_sf <- st_sf(geometry = grid)
grid_sf <- dist_points_to_path(grid_sf, tr) # Calculates crow distance from point to the path.

pts_grid <- do.call(rbind, st_geometry(grid_sf$geometry)) %>% 
    as_tibble() %>% setNames(c("x","y"))
pts_grid_cost <- extract_point_costs(cost_surface, pts_grid)
grid_sf <- cbind(grid_sf, pts_grid_cost)
grid_sf$pts_cost<-round(grid_sf$pts_grid_cost,1)

```


```{r}
library(cowplot)
```


```{r}
cost_v_dist <- 
  ggplot() +
  geom_point(data=grid_sf, mapping=aes(x=near_dist, y=pts_cost), colour="grey90") +
  geom_point(data=occ_wol_gda94, mapping=aes(x=near_dist, y=pts_cost, fill=status.native_anywhere_in_aus), shape=21, colour="black", size=2) +
  scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"),name = "Native Status") +
  new_scale_fill() +
  geom_point(data=introduced, mapping=aes(x=near_dist, y=pts_cost), shape=21, fill="#ABC7C9", colour="black", size=2) +
  theme_bw() + 
  theme(legend.position = c(0.98, 0.02),
    legend.justification = c(1, 0),
    legend.background = element_rect(fill = "white", colour = "grey80"),
    legend.key = element_rect(fill = "white"),
    plot.margin = margin(0, 0, 0, 0,  unit = "pt"),
    ) +
labs(title = NULL, x= "Distance (km)", y="Cost") +
    scale_x_continuous(expand = c(0.01,0.01)) +
   scale_y_continuous(expand = c(0.01,0.01))

dens1 <- 
  ggplot() + 
  geom_histogram(data=grid_sf, mapping=aes(x=near_dist), , bins = 100, position = "identity",fill="grey90", colour="grey90") +
  geom_histogram(data=occ_wol_gda94, mapping= aes(x = near_dist, fill = status.native_anywhere_in_aus), bins = 100, position = "identity",) + 
    scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"),name = "Native Status") +
 geom_histogram(data=introduced, mapping= aes(x = near_dist), bins = 100, position = "identity",fill="#ABC7C9") +    
    theme_bw() +
      theme(axis.line = element_blank(), 
  axis.text.x = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.x = element_blank(),
  legend.position = "none", 
  panel.border = element_blank(), 
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(0,0,0,0)
  )+
    scale_x_continuous(expand = c(0.01,0.01)) +
   scale_y_continuous(expand = c(0.01,0.01)) +
  labs( y="Count") 
   

dens2 <- 
  ggplot() + 
  geom_histogram(data=grid_sf, mapping=aes(x=pts_cost), bins = 100, position = "identity", fill="grey90", colour="grey90") +
  geom_histogram(data=occ_wol_gda94, mapping= aes(x = pts_cost, fill = status.native_anywhere_in_aus),bins = 100, position = "identity",) + 
  scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"),name = "Native Status") +
   geom_histogram(data=introduced, mapping= aes(x = pts_cost), bins = 100, position = "identity", fill="#ABC7C9") +
  theme_bw() + 
    theme(axis.line = element_blank(), 
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.y = element_blank(),
  legend.position = "none", 
  panel.border = element_blank(), 
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(0,0,0,0)
  )+
    scale_x_continuous(expand = c(0.01,0.01)) +
   scale_y_continuous(expand = c(0.01,0.01)) +
  labs( y="Count")+
  coord_flip()

dens1 + plot_spacer() + cost_v_dist + dens2 + 
 plot_layout(ncol = 2, nrow = 2, widths = c(8, 2), heights = c(2, 8))# & theme(plot.margin = margin(0,0,0,0))

ggsave(
  filename = paste0(WKDir,"output/plots/cost_v_dist.png"),
  width = 7,
  height = 7,
  dpi = 300
)
```




```{r}
tr_buff <- st_buffer(wol_tr_gda94, dist=30, nQuadSegs = 30)
crop_to_track <-terra::crop(cost, tr_buff, mask=TRUE, touches=TRUE)


tr_road <- tr_buff %>% filter(highway_com=="road")

setup_terra_for_large_rasters(
  tempdir = paste0(WKDir, "output/temp/"),
  memfrac = 0.6,
  verbose = TRUE
)

burn_tracks(crop_to_track, tr_road, filename=paste0(WKDir,"output/burn_tracks.tif"))
burn_tr <- terra::rast(paste0(WKDir,"output/burn_tracks.tif"))
# see if this runs without detaching tracks with no oragine
run_cost_dist(burn_tr, filename= (paste0(WKDir,"output/cost_track.tif")), tmp_fn= (paste0(WKDir,"output/temp/")), overwrite = TRUE, maxiter = 25)
cost_tr <- terra::rast(paste0(WKDir,"output/cost_track.tif"))

#plot cost track over original tracks so we can see if things are missing
```


```{r}
track_plot <- ggplot() +
  geom_sf(data = np_wol_gda94, aes(geometry=geometry), colour="grey30", fill= "black", lwd=1) +
  new_scale_fill() +
    # Tracks
      geom_sf(data = wol_tr_gda94, aes(geometry=geometry, color = highway_com), key_glyph = draw_key_path, lwd=0.6) +
          scale_color_manual(values=c("#7a7a7a","#4E4E4E","#E69F00","white")) +
              new_scale_fill() +
      geom_spatraster(data = cost_tr, maxcell=100000000) +
   scale_fill_gradientn(colours=grDevices::hcl.colors(50, "BluYl", rev = TRUE), na.value="transparent") +
      coord_sf() +
      theme_bw() + theme(panel.background = element_rect(fill = 'gray20', colour = 'grey20'), panel.grid.major = element_line(colour = "grey30")) +
  scale_x_continuous( expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
         labs(title = " Tracks")
ggsave(
  filename = paste0(WKDir,"output/plots/tracks_cost.png"),
  width = 40,
  height = 30,
  dpi = 300,
  plot=track_plot
)
```


```{r}
# class       : SpatRaster 
# size        : 64357, 44999, 1  (nrow, ncol, nlyr)
# resolution  : 2, 2  (x, y)
# extent      : 225016, 315014, 6287428, 6416142  (xmin, xmax, ymin, ymax)
# coord. ref. : GDA94 / MGA zone 56 (EPSG:28356) 
# source      : cost_track.tif 
# varname     : burn_tracks 
# name        :    layer 
# min value   :     0.00 
# max value   : 12007.47 
# 
# $benchmark
# $benchmark$elapsed_secs
# [1] 5195.66
# 
# $benchmark$peak_mem_mb
# [1] 165.3319
# 
# $benchmark$raster_dims
# [1] 64357 44999
# 
# $benchmark$n_cells
# [1] 2896000643
# 

```






























```{r}
# SMALL test 

# Creating small box
bbox <- ext(150.230, 150.280, -33.190, -33.140)
bbox_vect <- as.polygons(bbox)
crs(bbox_vect) <- "EPSG:4283"  
bbox_proj <- project(bbox_vect, crs(cost))
cost_crop_sm <- crop(cost, bbox_proj, mask = TRUE) # Cost
wol_tr_crop_sm <- st_crop(wol_tr_gda94, bbox_proj, mask = TRUE) # Tracks
plot(cost_crop_sm)

cost_sm <- load_cost_raster(cost_crop_sm)
track_sm <- load_tracks(wol_tr_crop_sm)
burn_sm <- burn_tracks(cost_sm, track_sm, tmp_fn= (paste0(WKDir,"output/temp/")))
cost_surface_sm<- run_cost_dist(burn_sm, filename= (paste0(WKDir,"output/cost_surface_sm.tif")), overwrite=TRUE)
cost_surface_sm <- terra::rast(paste0(WKDir,"output/cost_surface_sm.tif"))
plot_cost_with_tracks(cost_surface_sm, tracks = track_sm, filename = "output/plots/cost_rast_sm.png")

# Raster CRS: GDA94 / MGA zone 56 (EPSG:28356)
# Tracks CRS: GDA94 / MGA zone 56 (EPSG:28356)
# Raster dimensions: 2834 rows x 2405 cols (6,815,770 cells)
# Resolution: 2 x 2 m
# Rasterizing tracks onto cost surface...
# Track cells rasterized: 14,905 (0.22% of raster)
# Running costDist (maxiter=50)...
# costDist completed in 11.26 seconds
# Estimated peak memory: 143.9 MB
ext(cost_crop_sm)
```



```{r}
occ_wol_gda94 <- occ_wol_gda94 %>% filter(uncertainty < 300)
occ_wol_gda94_text <- occ_wol_gda94 %>% filter(pts_cost > 300)

fac <- c("red", "blue", "green")[factor(occ_wol_gda94$status.native_anywhere_in_aus)]

png(paste0(WKDir,"output/plots/cost_rast_wol.png"), width = 12000,height = 8800, res = 300, bg = "white")
#pdf(paste0(WKDir,"output/plots/cost_rast.pdf"), width = 50,height = 50)
plot(cost_surface_wol,
    main = "Cost Surface with Tracks", colNA = "black",
    col = grDevices::hcl.colors(50, "YlOrRd", rev = TRUE),
    maxcell=10000, #100000000,
    legend = TRUE
  )
plot(track, col = "dodgerblue", add = TRUE, legend = FALSE)
plot(mask,
     col = "white",
     border = NA,
     add = TRUE)
points(occ_wol_gda94$geometry,
      pch = 21, bg = fac, cex = 1.2, lwd = 1.5, col=fac, legend = TRUE)
text(occ_wol_gda94_text$geometry,
        labels = occ_wol_gda94_text$pts_cost,
        pos = 4, cex = 0.5, font = 2, offset = 0.3)
dev.off()
```
