---
title: "plots"
output: html_document
date: "2026-03-03"
---

```{r}
library(ggplot2)
library(tidyterra)
library(ggnewscale)
library(ggrepel)
library(patchwork)
```


# whole raster plot

```{r}
cost_plot <-  
  ggplot() +
  # cost surface 
      geom_spatraster(data = cost_surface_wol, maxcell=100000000) +
        scale_fill_gradientn(colours=grDevices::hcl.colors(50, "YlOrRd", rev = TRUE), na.value = "grey90", name="Cost") +
  # Tracks
      geom_sf(data = tr, aes(geometry=geometry, color = highway_com), key_glyph = draw_key_path, lwd=0.6) +
          scale_color_manual(values=c("#7a7a7a","#4E4E4E","#E69F00","black")) +
    ggnewscale::new_scale_fill() +
  ggnewscale::new_scale_colour() +
  # points
      geom_sf(data = occ_wol_cost, aes(fill = as.factor(status.native_anywhere_in_aus), col=source, geometry = geometry), shape = 21, size = 3, stroke = 1, inherit.aes = FALSE) +
          scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"), name = "Native Status") +
          scale_color_manual(values=c("#FFD700","black"),name = "Data Source") + # only include this when both herbarim and inat data are avalible. 
   # labels
      geom_text_repel(data = occ_wol_text, aes(label = pts_cost, geometry = geometry), stat = "sf_coordinates", size = 3, segment.size= 0.2,  max.overlaps = Inf) + #fontface = "bold",
  # plot design
      coord_sf() +
      theme_bw() + theme(legend.key = element_rect(fill="grey90")) +
  scale_x_continuous( expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
         labs(title = "Cost Surface with Tracks")
  
ggsave(
  filename = paste0(WKDir,"output/plots/cost_rast_wol.png"),
  width = 40,
  height = 30,
  dpi = 300
)

```

# tracks
```{r}
track_plot <- ggplot() +
  geom_sf(data = np_wol_gda94, aes(geometry=geometry), colour="grey30", fill= "black", lwd=1) +
  new_scale_fill() +
    # Tracks
      geom_sf(data = wol_tr_gda94, aes(geometry=geometry, color = highway_com), key_glyph = draw_key_path, lwd=0.6) +
          scale_color_manual(values=c("#7a7a7a","#4E4E4E","#E69F00","white")) +
              new_scale_fill() +
      geom_spatraster(data = cost_tr, maxcell=100000000) +
   scale_fill_gradientn(colours=grDevices::hcl.colors(50, "BluYl", rev = TRUE), na.value="transparent") +
      coord_sf() +
      theme_bw() + theme(panel.background = element_rect(fill = 'gray20', colour = 'grey20'), panel.grid.major = element_line(colour = "grey30")) +
  scale_x_continuous( expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
         labs(title = " Tracks")
ggsave(
  filename = paste0(WKDir,"output/plots/tracks_cost.png"),
  width = 40,
  height = 30,
  dpi = 300,
  plot=track_plot
)
```



iNaturalist
```{r}
cost_v_dist <- 
  ggplot() +
  geom_point(data=grid_sf, mapping=aes(x=near_dist, y=pts_cost), colour="grey90") +
  geom_point(data=occ_wol_gda94, mapping=aes(x=near_dist, y=pts_cost, fill=status.native_anywhere_in_aus), shape=21, colour="black", size=2) +
  scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"),name = "Native Status") +
  new_scale_fill() +
  geom_point(data=introduced, mapping=aes(x=near_dist, y=pts_cost), shape=21, fill="#ABC7C9", colour="black", size=2) +
  theme_bw() + 
  theme(legend.position = c(0.98, 0.02),
    legend.justification = c(1, 0),
    legend.background = element_rect(fill = "white", colour = "grey80"),
    legend.key = element_rect(fill = "white"),
    plot.margin = margin(0, 0, 0, 0,  unit = "pt"),
    ) +
labs(title = NULL, x= "Distance (km)", y="Cost") +
    scale_x_continuous(expand = c(0.01,0.01), trans='log') +
   scale_y_continuous(expand = c(0.01,0.01), trans='log')

dens1 <- 
  ggplot() + 
  geom_histogram(data=grid_sf, mapping=aes(x=near_dist), , bins = 100, position = "identity",fill="grey90", colour="grey90") +
  geom_histogram(data=occ_wol_gda94, mapping= aes(x = near_dist, fill = status.native_anywhere_in_aus), bins = 100, position = "identity",) + 
    scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"),name = "Native Status") +
 geom_histogram(data=introduced, mapping= aes(x = near_dist), bins = 100, position = "identity",fill="#ABC7C9") +    
    theme_bw() +
      theme(axis.line = element_blank(), 
  axis.text.x = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.x = element_blank(),
  legend.position = "none", 
  panel.border = element_blank(), 
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(0,0,0,0)
  )+
    scale_x_continuous(expand = c(0.01,0.01), trans='log') +
   scale_y_continuous(expand = c(0.01,0.01)) +
  labs( y="Count") 
   

dens2 <- 
  ggplot() + 
  geom_histogram(data=grid_sf, mapping=aes(x=pts_cost), bins = 100, position = "identity", fill="grey90", colour="grey90") +
  geom_histogram(data=occ_wol_gda94, mapping= aes(x = pts_cost, fill = status.native_anywhere_in_aus),bins = 100, position = "identity",) + 
  scale_fill_manual(values=c("#ABC7C9", "#666633", "#669900"),name = "Native Status") +
   geom_histogram(data=introduced, mapping= aes(x = pts_cost), bins = 100, position = "identity", fill="#ABC7C9") +
  theme_bw() + 
    theme(axis.line = element_blank(), 
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.y = element_blank(),
  legend.position = "none", 
  panel.border = element_blank(), 
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(0,0,0,0)
  )+
    scale_x_continuous(expand = c(0.01,0.01), trans='log') +
   scale_y_continuous(expand = c(0.01,0.01)) +
  labs( y="Count")+
  coord_flip()

dens1 + plot_spacer() + cost_v_dist + dens2 + 
 plot_layout(ncol = 2, nrow = 2, widths = c(8, 2), heights = c(2, 8))# & theme(plot.margin = margin(0,0,0,0))

ggsave(
  filename = paste0(WKDir,"output/plots/cost_v_dist_log.png"),
  width = 7,
  height = 7,
  dpi = 300
)
```

# Herbarium
```{r}
cost_v_dist <- 
  ggplot() +
  geom_point(data=grid_sf, mapping=aes(x=near_dist, y=pts_cost), colour="grey90") +
  geom_point(data=occ_wol_herb_gda94, mapping=aes(x=near_dist, y=pts_cost, fill=status.native_anywhere_in_aus), shape=21, colour="black", size=2) +
  scale_fill_manual(values=c( "#666633", "#669900"),name = "Native Status") +
  theme_bw() + 
  theme(legend.position = c(0.98, 0.02),
    legend.justification = c(1, 0),
    legend.background = element_rect(fill = "white", colour = "grey80"),
    legend.key = element_rect(fill = "white"),
    plot.margin = margin(0, 0, 0, 0,  unit = "pt"),
    ) +
labs(title = NULL, x= "Distance (km)", y="Cost") +
    scale_x_continuous(expand = c(0.01,0.01)) +
   scale_y_continuous(expand = c(0.01,0.01))

dens1 <- 
  ggplot() + 
  geom_histogram(data=grid_sf, mapping=aes(x=near_dist), , bins = 100, position = "identity",fill="grey90", colour="grey90") +
  geom_histogram(data=occ_wol_herb_gda94, mapping= aes(x = near_dist, fill = status.native_anywhere_in_aus), bins = 100, position = "identity",) + 
    scale_fill_manual(values=c("#666633", "#669900"),name = "Native Status") +
    theme_bw() +
      theme(axis.line = element_blank(), 
  axis.text.x = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.x = element_blank(),
  legend.position = "none", 
  panel.border = element_blank(), 
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(0,0,0,0)
  )+
    scale_x_continuous(expand = c(0.01,0.01)) +
   scale_y_continuous(expand = c(0.01,0.01)) +
  labs( y="Count") 
   

dens2 <- 
  ggplot() + 
  geom_histogram(data=grid_sf, mapping=aes(x=pts_cost), bins = 100, position = "identity", fill="grey90", colour="grey90") +
  geom_histogram(data=occ_wol_herb_gda94, mapping= aes(x = pts_cost, fill = status.native_anywhere_in_aus),bins = 100, position = "identity",) + 
  scale_fill_manual(values=c( "#666633", "#669900"),name = "Native Status") +
  theme_bw() + 
    theme(axis.line = element_blank(), 
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.y = element_blank(),
  legend.position = "none", 
  panel.border = element_blank(), 
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(0,0,0,0)
  )+
    scale_x_continuous(expand = c(0.01,0.01)) +
   scale_y_continuous(expand = c(0.01,0.01)) +
  labs( y="Count")+
  coord_flip()

dens1 + plot_spacer() + cost_v_dist + dens2 + 
 plot_layout(ncol = 2, nrow = 2, widths = c(8, 2), heights = c(2, 8))# & theme(plot.margin = margin(0,0,0,0))

ggsave(
  filename = paste0(WKDir,"output/plots/cost_v_dist_herb.png"),
  width = 7,
  height = 7,
  dpi = 300
)
```