---
title: "setup"
output: html_document
date: "2026-02-16"
---
```{r}
# set up files. 
WKDir ="/Users/z5161362/OneDrive - DPIE/Documents/PhD/spatRast/"

library(sf)
library(dplyr)
library(galah)
library(terra)
library(raster)
library(tictoc)

galah_config(email = "jordanmirandamay@gmail.com", atlas = "Australia")
source(paste0(WKDir,"R/functions.R"))
```

```{r}
# This is National parks official park boundaries
np <- read_sf(dsn = paste0(WKDir,"data_wol/tenure_npws_estateinternalboundaries/NPWS_EstateInternalBoundaries.shp"))
np_wol <- subset(np, np$NAME =="Wollemi National Park") #subset out Wollemi np from outer parks
np_wol_bound <- st_make_valid(np_wol) #fixing broken shapes
np_wol <- st_union(np_wol_bound) #tuning into one sf 
np_wol <- st_transform(np_wol, 4326)
np_wol_buff <- st_buffer(np_wol, dist = 2000, nQuadSegs = 30) # changed from 500 to 2000
np_wol_buff <- st_sfc(st_polygon(list(np_wol_buff[[1]][[1]])), crs = st_crs(np_wol_buff))
plot(np_wol_buff)
```

```{r}
# This is a shape from qgis.This is used for downloading occurrence records.
wol_bound <- read_sf(dsn = paste0(WKDir,"data_wol/bounds/wol_bound_v3.shp")) 
#plot(wol_bound)
```

```{r}
#This is tracks from open street maps, filtered to Wollemi, surprisingly good!
wol <- read_sf(dsn = paste0(WKDir,"data_wol/tracks/tracks_wol_v2.shp"))
#plot(wol$geometry)

wol_tr <- st_intersection(wol,np_wol_buff) 

wol_tr <- wol_tr[wol_tr$highway!="construction",]
wol_tr$highway_com <- wol_tr$highway

wol_tr <- wol_tr %>%
  mutate(highway_com = case_when(
    highway %in% c("primary", "secondary", "tertiary") ~ "road",
    highway %in% c("residential", "unclassified", "service", "escape") ~ "access track",
    highway %in% c("track") ~ "track",
    highway %in% c("footway", "steps", "path") ~ "path",))

plot(wol_tr$geometry)
```

```{r}
# Getting occurrences records
occ_wol_inat_all <- galah_call() |>
  galah_identify("Plantae") |>
  geolocate(wol_bound) |>
  galah_filter(
    dataResourceName == "iNaturalist Australia",
    imageIDsCount >=1
  ) |>
  galah_select(institutionID, informationWithheld, raw_informationWithheld,occurrenceID,coordinateUncertaintyInMeters, group = "basic") |>
  atlas_occurrences()

occ_wol_inat <- occ_wol_inat_all %>% filter(is.na(raw_informationWithheld))

#turning occurrences records into shape file for compatibility
occ_wol_sp <- galah_record_to_sf (occ_wol_inat)
#filtering to match national park shapefile
occ_wol <- st_filter(occ_wol_sp, np_wol)
```

```{r}
# Getting occurrences records
occ_wol_herb_all <- galah_call() |>
  galah_identify("Plantae") |>
  geolocate(wol_bound) |>
  galah_filter(
    basisOfRecord == "PRESERVED_SPECIMEN",
    imageIDsCount >=1,
    year >= 2010
  ) |>
  galah_select(institutionID, informationWithheld, raw_informationWithheld,occurrenceID,coordinateUncertaintyInMeters, verbatimLatitude, verbatimLongitude, group = "basic")  |>
atlas_occurrences()

occ_wol_herb <- occ_wol_herb_all %>% filter(!is.na(eventDate))


#turning occurrences records into shape file for compatibility
occ_wol_herb_sp <- galah_record_to_sf (occ_wol_herb)
#filtering to match national park shapefile
occ_wol_herb <- st_filter(occ_wol_herb_sp, np_wol)
```


```{r}
#This section just runs once. It takes the DEM and saves a slope rater than can be loaded in, in the next section.
#only run once, takes a long time and is memory intensive.
file = "data_wol/DEM/Elevation/2 Metre/"
filename =list.files(path=paste0(WKDir,file), pattern = ".tif", full.names = FALSE, recursive = FALSE)
rasters_2 <- lapply(filename, function(fn) terra::rast(paste0(WKDir, file, fn)))
merged_2  <- do.call(mosaic, c(rasters_2, fun=mean))



file = "data_wol/DEM/Elevation/1 Metre/"
filename =list.files(path=paste0(WKDir,file), pattern = ".tif", full.names = FALSE, recursive = FALSE)

        all_crs <- sapply(paste0(file,filename), function(f) crs(rast(f)))
        unique_crs <- unique(all_crs)
        merged_groups <- list()
        for (i in seq_along(unique_crs)) {
            target <- unique_crs[i]
            group_files <- paste0(file, filename)[all_crs == target]
            # Load tiles for group
            group_rasters <- lapply(group_files, rast)
            # Merge group
            merged_groups[[i]] <- do.call(mosaic, c(group_rasters, fun = mean))
        }
         plot(merged_groups[[1]])
         plot(merged_groups[[2]])
        # crs(merged_groups[[1]])
        # LHS <- terra::project(merged_groups[[1]], crs(merged_groups[[2]]))
        # LHS <- resample(LHS, extend(merged_groups[[2]],LHS), method = "bilinear")
        # merged_2 <- mosaic(LHS, merged_groups[[2]], fun = mean)

rasters_1 <- lapply(filename, function(fn) terra::rast(paste0(WKDir, file, fn)))
merged_1  <- do.call(mosaic, c(rasters_1, fun=mean))
ras_1 <- terra::aggregate(merged_1, fact = 2, fun = mean)

stiched <- terra::merge(ras_1, merged_2)
terra::writeRaster(stiched, paste0(WKDir, "data_wol/DEM/stiched.tif"), overwrite = TRUE) #temp file until storage issues have been solved. 
rm(ras_1, merged_2, stiched,)

np_wol_buff_gda94 <- sf::st_transform(np_wol_buff, crs = crs(stiched))
stiched_wol <- terra::crop(stiched, vect(np_wol_buff_gda94), mask=TRUE)
slope <- terra::terrain(stiched_wol, v="slope", unit="degrees", neighbors=8)

#terra::writeRaster(slope, paste0(WKDir, "data/DEM/slope.tif"), overwrite = TRUE) ## Commented out to prevent re-writing
slope <- terra::rast(paste0(WKDir, "data_wol/DEM/slope.tif")) # slope from Elvis DEM tiles
slope_wol_save <- terra::crop(slope, vect(np_wol_buff_gda94), mask=TRUE) # This line takes a while. Try and keep loaded
#terra::writeRaster(slope_wol_save, paste0(WKDir, "data/DEM/slope_wol.tif"), overwrite = TRUE) ## Commented out to prevent re-writing
rm(ras_1, merged_2, stiched, slope_wol_save)
```



```{r}
slope_wol <- terra::rast(paste0(WKDir, "data_wol/DEM/slope_wol.tif")) # slope from Elvis DEM tiles
# Transfering data to DEM CRS = 4283
np_wol_gda94 <- st_transform(np_wol, crs = crs(slope_wol)) # Outline
np_wol_buff_gda94 <- st_transform(np_wol_buff, crs = crs(slope_wol)) # Buffer
wol_tr_gda94 <- st_transform(wol_tr, crs = crs(slope_wol)) # Tracks
occ_wol_gda94 <- st_transform(occ_wol, crs = crs(slope_wol)) # iNaturalist occurrences
occ_wol_herb_gda94 <- st_transform(occ_wol_herb, crs = crs(slope_wol)) # herbarium occurrences
#saveRDS(wol_tr_gda94, paste0(WKDir,"data/tracks/tracks_clean.rds"))
```


```{r}
# Transferring via Toblers Hiking function
f_exp <- function(x) {
  speed <- 0.6 * (6 * exp(-3.5 * abs(x / 100 + 0.05)))  # km/h (off-track adjusted)
  ifelse(x > 70, NA, 1 / (speed * 1000))                # hours per metre
}

cost <- app(slope_wol, f_exp,
             filename=paste0(WKDir,"data_wol/processing/wol/cost.tif"),
             overwrite=TRUE)
plot(cost)
```

